### ISSUE TITLE
Running in the background (hack)

### ISSUE THREAD

**Issue by dangreenisrael** [chendo/lifx-http#12]
I get the server running in the background, and deal with it potentially crashing by running this php script as a cron:
```
// This lets me run the script on an interval
exec('pkill lifx-http');
echo "killed LIFX";

// The nohum and & let me keep running commands after the server is launched
$command = 'lifx-http';
exec("nohup $command >/dev/null 2>/dev/null &"); 
echo 'started LIFX server';

// I exit the script to prevent any system hang
exit;
```

**Comment by justinatomatic** [comment]
If your using RVM you can generate wrapper scripts and then run lifx-httpd with any process control app. 

I've got it working with supervisor. 

http://omaticlabs.com/homepage/24/lifx-http-supervisor
